dependency_order:
  - Program
  - Project
  - Organization
  - Location
  - Practitioner
  - PractitionerRole
  - ResearchStudy
  - Patient
  - ResearchSubject
  - Specimen
  - Encounter
  - Observation
  - DiagnosticReport
  - Condition
  - Medication
  - MedicationRequest
  - ImagingStudy
  - Procedure
  - Questionnaire
  - QuestionnaireResponse
  - DocumentReference
  - Task
entities:
#  CodeableConcept:
#    category: Administrative
#    id: CodeableConcept
#    links: {}
#    source: null
#  Coding:
#    category: Administrative
#    id: Coding
#    links: {}
#    source: null

  Condition:
    category: Clinical
    id: Condition
    links:
      asserter:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      encounter:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Encounter'
      recorder:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      subject:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
    source: null
  DiagnosticReport:
    category: Clinical
    id: DiagnosticReport
    links:
      basedOn:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      encounter:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Encounter'
      imagingStudy:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/ImagingStudy'
      performer:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Practitioner'
          - 'http://hl7.org/fhir/StructureDefinition/Organization'
          - 'http://hl7.org/fhir/StructureDefinition/PractitionerRole'
      result:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Observation'
      resultsInterpreter:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      specimen:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Specimen'
      subject:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
    source: null
  DocumentReference:
    category: data_file
    id: DocumentReference
    links:
      authenticator:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      author:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      custodian:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      relatesTo:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      subject:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
    source: >-
      https://nih-ncpi.github.io/ncpi-fhir-ig/StructureDefinition-ncpi-drs-document-reference.json
  Encounter:
    category: Clinical
    id: Encounter
    links:
      account:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      appointment:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      basedOn:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      episodeOfCare:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      partOf:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      reasonReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      serviceProvider:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      subject:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
    source: null
  ImagingStudy:
    category: Clinical
    id: ImagingStudy
    links:
      basedOn:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      encounter:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      endpoint:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      interpreter:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      location:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      procedureReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      reasonReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      referrer:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      subject:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
    source: null
  Location:
    category: Administrative
    id: Location
    links:
      endpoint:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      managingOrganization:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      partOf:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
    source: null
  Medication:
    category: Clinical
    id: Medication
    links:
      manufacturer:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
    source: null
  MedicationRequest:
    category: Clinical
    id: MedicationRequest
    links:
      basedOn:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      detectedIssue:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      encounter:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Encounter'
      eventHistory:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      insurance:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      medicationReference:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Medication'
      performer:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      priorPrescription:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      reasonReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      recorder:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      reportedReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      requester:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      subject:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
      supportingInformation:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
    source: null
  Observation:
    category: Clinical
    id: Observation
    links:
      basedOn:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      derivedFrom:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      device:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      encounter:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Encounter'
      focus:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
          - 'http://hl7.org/fhir/StructureDefinition/Specimen'
      hasMember:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      partOf:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      performer:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      specimen:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Specimen'
      subject:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
          - 'http://hl7.org/fhir/StructureDefinition/ResearchStudy'
    source: null
  Organization:
    category: Administrative
    id: Organization
    links:
      endpoint:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      partOf:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
    source: null
  Patient:
    category: Administrative
    id: Patient
    links:
      generalPractitioner:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Practitioner'
      managingOrganization:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Organization'
    source: null
  Practitioner:
    category: Administrative
    id: Practitioner
    links: {}
    source: null
  PractitionerRole:
    category: Administrative
    id: PractitionerRole
    links:
      endpoint:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      healthcareService:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      location:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      organization:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Organization'
      practitioner:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Practitioner'
    source: null
  Procedure:
    category: Clinical
    id: Procedure
    links:
      asserter:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      basedOn:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      complicationDetail:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      encounter:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Encounter'
      location:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Location'
      partOf:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      reasonReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      recorder:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      report:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      subject:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      usedReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
    source: null
  ResearchStudy:
    category: Administrative
    id: ResearchStudy
    links:
      enrollment:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      partOf:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      principalInvestigator:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      project:
        ignore: false
        required: true
        targetProfile:
          - project
      protocol:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      site:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      sponsor:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
    source: null
  ResearchSubject:
    category: Administrative
    id: ResearchSubject
    links:
      consent:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      individual:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
      study:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/ResearchStudy'
    source: null
  Specimen:
    category: Biospecimen
    id: Specimen
    links:
      parent:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Specimen'
      request:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      subject:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
    source: null
  Task:
    category: Analysis
    id: Task
    links:
      basedOn:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      encounter:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      focus:
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Specimen'
      for:
        ignore: false
        required: true
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/Patient'
      for_fhir:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      insurance:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      location:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      output:
        ignore: false
        required: true
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/DocumentReference'
      owner:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      partOf:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      reasonReference:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      relevantHistory:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
      requester:
        ignore: true
        required: false
        targetProfile:
          - 'http://hl7.org/fhir/StructureDefinition/%UNKNOWN%'
    source: >-
      https://nih-ncpi.github.io/ncpi-fhir-ig/StructureDefinition-ncpi-specimen-task.json
ignored_properties:
  - contained
  - meta
  - implicitRules
#  - language
  - contained
  - modifierExtension
  - assigner
